### ISSUE TITLE
Can't run train script

### ISSUE THREAD

**Issue by pyrito** [JannerM/trajectory-transformer#1]
Hi I keep getting an error from this line: `from tap import Tap`

What is this module? I can't seem to find it properly and it's not working well.

**Comment by pyrito** [comment]
I think I figured it out. Sorry!

**Comment by jannerm** [comment]
Glad you figured it out! In case anyone else runs into this issue: tap is the import name for [typed-argument-parser](https://github.com/swansonk14/typed-argument-parser). It's included in the environment file [here](https://github.com/JannerM/trajectory-transformer/blob/344304c1cc8d8130e339bfb024c450e3bebdd434/environment.yml#L18).
