### ISSUE TITLE
Pretrained Model in AntMaze

### ISSUE THREAD

**Issue by TsuTikgiau** [JannerM/trajectory-transformer#11]
Hello, I'm interested in the AntMaze tasks and notice that currently the pretrained models in AntMaze are not provided. Will you provide the pretrained models in AntMaze in the future? Thank you!

**Comment by jannerm** [comment]
Sure thing. If you send me your email address, I can share them with you now.

**Comment by TsuTikgiau** [comment]
hello, my email address is tsu.tikgiau@gmail.com. Thank you!

**Comment by jannerm** [comment]
Shared, and sent an email with instructions for running. Let me know how it goes!
