### ISSUE TITLE
No registered env with id: halfcheetah-medium-v2

### ISSUE THREAD

**Issue by QuBohao** [JannerM/trajectory-transformer#7]
When I run "python scripts/train.py --dataset halfcheetah-medium-v2", then exception occurred : "gym.error.UnregisteredEnv: No registered env with id: halfcheetah-medium-v2".  And my gym version and mujoco version are all same as environment.yml

**Comment by jannerm** [comment]
This environment should be registered upon importing `d4rl`, so my guess is that something is wrong with the `d4rl` installation. You can check your installation by running:
```
python -c "import d4rl; print([k for k in d4rl.infos.DATASET_URLS.keys() if 'halfcheetah' in k])"
```
There should be a list of halfcheetah environments printed out.

Alternatively, you can use my docker image with:
```
docker pull jannerm/trajectory
```
for something that will work out of the box.
